name: Deploy Frontend

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # 或者使用你本地使用的 Node 版本

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build:h5

      - name: Clean Remote Directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            mkdir -p /var/www/studio/dist2
            rm -rf /var/www/studio/dist2/*

      - name: Deploy to Server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: "dist/build/h5"
          target: "/var/www/studio/dist2"
          strip_components: 3
